services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: expensescontrol_frontend
        restart: unless-stopped
        ports:
            - "127.0.0.1:3002:80"
