import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'secondary-container': '#6cf8bb',
        'inverse-surface': '#213145',
        'positive-emerald': '#10B981',
        'tertiary-container': '#002e37',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'inverse-primary': '#aec9ea',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#4cd7f6',
        'border-subtle': '#E2E8F0',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed-variant': '#2e4964',
        'secondary-fixed': '#6ffbbe',
        background: '#f8f9ff',
        'on-tertiary-container': '#009eb9',
        primary: '#00162a',
        secondary: '#006c49',
        'primary-container': '#0d2b45',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004e5c',
        'surface-container-highest': '#d3e4fe',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#acedff',
        'on-primary-container': '#7893b2',
        outline: '#73777e',
        'surface-container-high': '#dce9ff',
        'surface-tint': '#46607d',
        'on-error': '#ffffff',
        'surface-variant': '#d3e4fe',
        'secondary-fixed-dim': '#4edea3',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001d35',
        'on-secondary-container': '#00714d',
        tertiary: '#00181e',
        'on-surface-variant': '#43474d',
        'warning-amber': '#F59E0B',
        'on-primary': '#ffffff',
        'background-surface': '#F8FAFC',
        'inverse-on-surface': '#eaf1ff',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'negative-rose': '#F43F5E',
        'negative-rose-dark': '#c1314a',
        'outline-variant': '#c3c6ce',
        'on-secondary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'primary-fixed': '#d0e4ff',
        'on-secondary-fixed': '#002113',
        'primary-fixed-dim': '#aec9ea',
        'on-tertiary-fixed': '#001f26',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
        'label-numeric': ['JetBrains Mono'],
        'title-md': ['Hanken Grotesk'],
        'label-caps': ['Inter'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'body-sm': ['Inter'],
      },
    },
  },
  plugins: [],
} satisfies Config
